### ISSUE TITLE
"process" not defined in threadman.js 

### ISSUE THREAD

**Issue by RohinJoshi1** [iden3/ffjavascript#100]
<img width="523" alt="Screenshot 2023-03-27 at 9 11 23 AM" src="https://user-images.githubusercontent.com/74340187/227835393-57eab9f6-e542-49ce-a305-ff7b7ccee91e.png">

I'm creating a react project which is using this library as a dependency, I believe the fix would be to change "process.browser " to typeof window === 'undefined' , as process.browser has been deprecated

**Comment by StrawberryChocolateFudge** [comment]
Same problem with a rollup build. But I used this lib with parcel + react before and never had this problem.

**Comment by phated** [comment]
You can inject values into your bundle.
