### ISSUE TITLE
wanna try out a new worker?

### ISSUE THREAD

**Issue by jimmywarting** [iden3/ffjavascript#104]
I have developed a new web worker for nodejs with a bit enhancement over the original author. 
it supports creating web worker from blob urls. so you don't have to make any weird complicated base64 urls
URL and blobs are supported in nodejs too nowdays

```js
import Worker from 'whatwg-worker'
const code = 'console.log(1)'
const blob = new Blob([code], { type: 'text/javascript' })
const url = URL.createObjectURL(blob)

worker = new Worker(url)
```
Works the same way in both browser and nodejs
ofc if you would like to see fewer dependencies i highly suggest you to give this https://github.com/nodejs/node/issues/43583 a 👍

**Comment by phated** [comment]
I think we'll stick with our current implementation until node matches the global worker syntax.
