### ISSUE TITLE
Use Promise instead of async-await inside workers to make compatible with Babel

### ISSUE THREAD

**Issue by cryptopapi997** [iden3/ffjavascript#111]
First, thanks for this great library that takes a lot of work off my hands :).  One issue with it though is that it currently does not work with many Babel configurations due to the way Babel hoists polyfills to the top of the bundle (exact details and extended discussion on why this shouldn't be changed inside of Babel [here](https://github.com/babel/babel/issues/15425)  ). 

The fix to make ffjavascript work with any Babel config would be quite simple and is something we already implemented in a fork of our own [here](https://github.com/elusiv-privacy/ffjavascript), it just entails replacing async-await with a Promise within the worker threads. This doesn't require a lot of effort and shouldn't break anything for anyone, as any environment that supports async-await also supports Promise. Happy to open a PR for this myself unless there's some reason why ffjavascript prefers not to implement this. Thanks! :smile:

**Comment by phated** [comment]
This isn't something we want to do. You should stop trying to transpile async/await, as it is supported in 95.91% of browsers in use: https://caniuse.com/async-functions
