### ISSUE TITLE
Switch to native bigints

### ISSUE THREAD

**Issue by paulmillr** [iden3/ffjavascript#43]
Hi. I work with EF and ethereumjs teams on supply chain security.

Last 6 months i've been helping to move the ETH ecosystem to native bigints. Their time has come. They are not less secure when compared to 3rd party js modules with regards to timing attacks etc. We're a few weeks away from a major ethereumjs-util release, ethers is also using native bigints in their beta.

Since almost every ETH app depend on either ethereumjs-util, or ethers, this would mean the majority of them would be covered.

So, it would be great if ffjavascript did the switch, because many important libraries depend on it.

**Comment by phated** [comment]
👋 Hey Paul, didn't know you worked with EF! I'm planning to do this update very soon. We had a recent internal chat about it. The primary concern was bigint support in Safari, but I believe that's good to go, yeah?

**Comment by paulmillr** [comment]
Hey Blaine, didn't know you maintain this!

Good to hear. Do you need any help? Maybe I could take a glance over low-hanging fruits.

**Comment by phated** [comment]
Oh, one other thing that I found in the repo history was that someone PR'd using `BigInt()` syntax instead of the literal because the literal couldn't be parsed by babel. I'm not sure if that is still the case, but we'd want to find out or just keep using `BigInt()` syntax.

**Comment by paulmillr** [comment]
Babel parses it fine, it's some version of react native, or some shitty babel config, which can cause issues. But it can cause issues even with ** pow operator

**Comment by paulmillr** [comment]
https://github.com/facebook/react-native/pull/34589
