### ISSUE TITLE
Browser detection with a deprecated method

### ISSUE THREAD

**Issue by NadavPeled1998** [iden3/ffjavascript#55]
As you can see in this issue process.browser is deprecated, and you should use `typeof window === "undefined"`.
https://github.com/vercel/next.js/issues/5354#issuecomment-520305040

**Comment by phated** [comment]
Just because Next.js made this decision does not mean that every tool has made that decision.

**Comment by NadavPeled1998** [comment]
I'll try to explain myself again.

It's not just Next.js. It seems like using process.browser to detect if the code is running on the browser side was common practice a few years ago, but it's not the case anymore.

If you want to check what the process.browser is on a specific website, all you need to do is to open the inspector, go to the console and write process.browser.
I checked what process.browser is on all those websites is: 

- [Facebook](https://www.facebook.com/) - don't have a process object. throws an error if you try to access the process.browser
- [Github](https://github.com/) - don't have a process object. throws an error if you try to access the process.browser
- [Google](https://www.google.com/) -  don't have a process object. throws an error if you try to access the process.browser
- [Youtube](https://www.youtube.com/) - don't have a process object. throws an error if you try to access the process.browser
- [Twitter](https://twitter.com/home) - don't have a process object. throws an error if you try to access the process.browser
- [Uniswap](https://app.uniswap.org/) -  don't have a process object. throws an error if you try to access the process.browser
- [Tornado cash classic](https://tornadocash.eth.limo/) - don't have a process object. throws an error if you try to access the process.browser
-  [Tornado cash nova](https://nova.tornadocash.eth.limo/) - don't have process object. throws an error if you try to access the process.browser
-  [Circom docs](https://docs.circom.io/) - don't have a process object. throws an error if you try to access the process.browser
- [Opensea](https://opensea.io/) - don't have process object at all. throws an error if you try to access the process.browser
-  [Alchemy](https://www.alchemy.com/) - don't have a process object. throws an error if you try to access the process.browser
-  [Dark forest](https://zkga.me/) - don't have a process object. throws an error if you try to access the process.browser
- [Stackoverflow](https://stackoverflow.com/) - don't have a process object. throws an error if you try to access the process.browser
- [Npmjs](https://www.npmjs.com/) - have process object, but process.browser is undefined.

**I couldn't find even one website that his process.browser is defined.**

That means that in all those websites if they would use the ffjavascript library, and even if they just would use the circomlibjs library (that library uses ffjavacript as a dependency, and this is how I found out this issue), they would probably tackle with bugs because of that. 
Of course, if they would use only the functions that are not using process.browser. In that case, it will be ok (this is why tornado cash succeeds in using this library although this issue). 
But, if they would use a function that is supposed to work differently between browser and server, the library will handle that function like it's running on the server side, and it probably would fail.

I'll open a PR to fix that issue soon. I hope that you'll find this PR helpful.

**Comment by phated** [comment]
`process.browser` is not something that is defined globally. It is a variable that is injected into a build so we can do dead-code elimination. By trying to switch this to `typeof window === 'undefined` we can no longer DCE because you made it dynamic (and we **should not** be injecting `window`.
